### ISSUE TITLE
conserv

### ISSUE THREAD

**Issue by zkat** [sshirokov/hinge#1]
Hey,

I've been developing something very similar to this. You can check it out at http://github.com/sykopomp/conserv. I'd been thinking of trying to use libev instead of iolib to see if there was any difference in performance and portability. How has cl-ev been working out for you?

**Comment by zkat** [comment]
(I meant to message you, but github isn't letting me)

**Comment by sshirokov** [comment]
I like `cl-ev' it's young, so I've had to make slight patches and smooth things out as I use them, but nothing significant.

It's a pleasant experience if you don't mind getting your hands a little dirty, but I think it's worth it in the end.
